ripe-tech/ripe-sdk

gulpfile.js, src/js/api/admin.js, src/js/api/build.js, src/js/api/index.js
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-white/issues/127 |
| Decisions | SDK support for new ripe-core endpoint that returns information about a specific build, given the brand name and build version. [PR ripe-core](https://github.com/ripe-tech/ripe-core/pull/4433)|
=> Build info endpoint

src/js/base/ripe.js, src/js/visual/configurator.js, src/js/visual/image.js
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-white/issues/178 |
| Decisions | Added `pre_initials`, `post_initials`, `pre_initials_extra`, `post_initials_extra` and `not_loaded`events. The last 2 ones are for images and configurators that receive an update request but don't load a new image. |
| Animated GIF | - |
=> #178: New events for loading time

src/js/visual/configurator.js
| - | - |
| --- | --- |
| Decisions | `setAttribute` was supposed to clean the `src` on the mask `<img>` that triggered the error, but was called on `self` which doesn't even define such a method. |
=> Fix mask error handler

src/js/base/api.js
| - | - |
| --- | --- |
| Decisions | There are scenarios where's it's useful to invalidate the cache before making the request. This is different from making a request with no cache at all because we still want to populate it. An example would be: mutate some list and then refresh it. Because we've just mutated the list we know the cache has gone stale and would enjoy an update.  |
=> Cache invalidation for network requests

src/js/base/interactable.js, src/js/base/observable.js, src/js/base/ripe.js, src/js/visual/configurator.js, src/js/visual/image.js, src/js/visual/visual.js, src/python/ripe_demo/static/js/main.js, test/js/visual.js
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-white/issues/341 |
| Decisions | • **The symptoms of the problem:**<br>In the same build, when changing models with different number of thumbnails, in this case in brand "dummy", from the model "macho", "cube" or "bill", to the model "dummy", which will go from 3 thumbnails to 2 thumbails, the model can't be switched back. (See  [#341](https://github.com/ripe-tech/ripe-white/issues/341) for more details)<br>• **What the root cause issue was:**<br>`cancel` operation in two of the `Image`s would not be resolved so they would hang ripe-white. It would hang here:https://github.com/ripe-tech/ripe-sdk/blob/3450aa661f7fee03a9003c29ac89b64ffc18dc92/src/js/visual/image.js#L153 which would then hang here: …
=> #341 Fixes hanging white, when removing "Image"

src/js/visual/image.js
| - | - |
| --- | --- |
| Issue | Fixes https://github.com/ripe-tech/ripe-retail-vendors/issues/42 |
| Decisions | When we had the [frame name hack](https://github.com/ripe-tech/ripe-sdk/commit/569d437409617bcf4e44f051d5690c34d9d044d2) in place, `Image`s with `frame = 0` (the default) would result in a request to RIPE Core without a defined frame. The removal of that hack in conjunction with the fallback in the constructor that I'm not removing made it impossible to request the binding of an `Image` without a pre-defined frame. Doing that is useful whenever we want to fallback to the build configuration to define the best frame to view a certain image configuration. An example is relying on `spec.json`'s `defaults`, which might define "the one that best displays" a part, which is what …
=> Allow for an image without defined frame

src/js/base/api.js, src/js/base/auth.js
```
1) Auth
#auth key
should be able to authenticate with key:
Error: Authorization requested but none is available
at ripe.Ripe._build (src/js/base/api.js:799:15)
at ripe.Ripe.accountMe (src/js/api/account.js:30:20)
at ripe.Ripe.authKey (src/js/base/auth.js:215:10)
at ./repos/ripe-sdk/src/js/base/auth.js:237:14
at new Promise (<anonymous>)
at ripe.Ripe.authKeyP (src/js/base/auth.js:236:12)
at Context.<anonymous> (test/js/base/auth.js:39:35)
at processImmediate (internal/timers.js:456:21)
```
=> Fix authentication with key

src/js/api/account.js
| - | - |
| --- | --- |
| Issue | Method `accountMeP` isn't working because `this.me` isn't defined. |
| Decisions | Fix method `accountMeP`with the right corresponding method. |
=> Fix method name of accountMe

src/js/visual/configurator.js, src/js/visual/image.js
| - | - |
| --- | --- |
| Issue | Related to https://github.com/ripe-tech/ripe-sdk-components-vue/issues/6 |
| Decisions | There was no way of resizing an image after its initiation. The `resize` method updates the `size` parameter and calls the `update` method of `Image`, which updates it to a new state. |
| Animated GIF | Example: <br> ![Jul-23-2020 11-40-24](https://user-images.githubusercontent.com/25725586/88277908-686a7c00-ccd9-11ea-8a82-7a7eb041ffe6.gif)|
=> Resize method for Image

src/js/visual/configurator.js
| - | - |
| --- | --- |
| Issue | Related to https://github.com/ripe-tech/ripe-sdk-components-vue/issues/1. It is necessary to make the `configurator` solution more resilient to wrong input. |
| Decisions | When an invalid frame is given, and exception is transported to the higher level. However, if a valid frame is later given, it will be ignored since the class `animating` is still applied to the `configurator`. It is necessary to catch the exception thrown by `update` when an invalid frame is given and remove that class, not allowing the recursive action to continue and making it possible to later give a valid frame. |
| Animated GIF | **Before:** <br> ![Jul-23-2020 11-23-17](https://user-images.githubusercontent.com/25725586/88276529-1b85a600-ccd7-11ea-8545-ce0de0 …
=> Support for invalid frame error handling

src/js/visual/image.js
| - | - |
| --- | --- |
| Issue | Related to https://github.com/ripe-tech/ripe-sdk-components-vue/issues/3 |
| Decisions | When an image is created, there is no way of changing the options (eg. crop, format, initialsGroup, etc.) after its initialization. Since the method `update` already received options but was not using it, changes were made to allow overriding the already defined options with the ones provided. <br><br> A method for changing the `showInitials` flag was also added, allowing for the disabling of the personalization visualization.  <br><br>**Reasoning**: These two changes are necessary to implement prop reactivity, meaning that after the image component is initialized, already defined options might need changing. Since all changes are connected to …
=> Image update options

src/js/base/interactable.js, src/js/base/observable.js, src/js/visual/configurator.js
| - | - |
| --- | --- |
| Issue | Related to https://github.com/ripe-tech/ripe-sdk-components-vue/issues/2 |
| Decisions | Method to update configurator options (format, sensitivity, configAnimate, duration, etc) after its initialization. <br><br> **Reasoning**: The configurator components needs a way of updating the configurator options, which was impossible after its initialization. |
=> Update options in configurator after initialization

src/js/base/api.js, test/js/api/brand.js
| - | - |
| --- | --- |
| Decisions | Only parse JSON when the content-type matches, otherwise return the raw response. The adapter that uses `XMLHttpRequest` was already dealing with this so it didn't need adapting. Motivated by the need to call the logic methods from builds that don't translate to JSON, such as `supported_characters`, which return strings or numbers. <br/> This change changed the expectations of calling `minimum_initials` and `maximum_initials` through `runLogicP`, since it now returns a String rather than a Number because the `runLogic` response is not JSON and therefore should not be converted (so we lose the `JSON.parse("1")` that was converting the response to `Number`). Maybe there could be a specific RIPE SDK method to get the minimum and maximum initials as …
=> Fix non-JSON request parsing

src/js/visual/configurator-prc.js
| - | - |
| --- | --- |
| Decisions | There is no usage of this variable on the SDK, other than setting or updating this variable, so it should be removed from the Configurator. |
=> Removed unused interval variable

src/js/base/compat.js
| - | - |
| --- | --- |
| Issue | Closes #195 |
| Decisions | Checks to see if it is using webpack and the window is not defined. If so, uses the npm packages. Uses `__non_webpack_require__` to import `xmlhttprequest`, which is not defined by the `webpack's require`. This allows for no configuration in the `ripe-sdk`'s clients, as well as almost no changes in the existing code. |
| References |  • https://github.com/webpack/webpack/issues/11455 <br> • https://stackoverflow.com/questions/46185302/non-webpack-require-is-not-defined <br> • https://stackoverflow.com/questions/42797313/webpack-dynamic-module-loader-by-require | 
| Animated GIF | `epir-papyrus` with sdk, build with `nuxt build --standalone` and `nuxt start`: <br> ![Sep-28-2020 …
=> #195: RIPE SDK compatibility with Nuxt.js under Vercel

src/js/base/compat.js
| - | - |
| --- | --- |
| Issue | #202 |
| Decisions | Added workaround similar to react-native one, where the dependency name is assigned to a variable. However, it launches a warning `Critical dependency: the request of a dependency is an expression`.  The warning does not affect the build. <br> This fix does not require any change in the clients of the sdk. |
=> #202: Workaround for webpack static analysis of xmlhttprequst package import

src/js/base/api.js, test/js/api/brand.js
| - | - |
| --- | --- |
| Issue | Derived from https://github.com/ripe-tech/ripe-compose/issues/84 |
| Decisions | Support for `text/plain` response types without the need for `.text()` call. |
=> Added text/plain contentType for response

src/js/api/brand.js, test/js/api/brand.js
| - | - |
| --- | --- |
| Issue | The problem mentioned in the daily, that when passing the context or other options as `data` to the `runLogicP` method, that data does not reach `ripe-core`. |
| Decisions | The problem was that both fields `data` and `dataJ` where being passed to yonius. Yonius ignores the `dataJ` if `data` is defined, and adds the `data` to the URL as parameters (as expected), instead of sending it in the request body <br> https://github.com/hivesolutions/yonius/blob/b952ad890b82123009b735e3cdc8c467c9b195b8/js/api/api.js#L119 <br> It is necessary to delete the `data` field when creating the request. Tested by making request, the data is now reaching `ripe-core` and being passed to the method in the model logic script. |
=> DataJ problem in _runLogicOptions

src/js/api/config.js
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/3db/issues/46#issuecomment-749085566 |
| Decisions | Based on https://github.com/ripe-tech/ripe-core/blob/107411b442473779b0fd6003823cddc139057796/src/ripe_core/controllers/api/config.py#L22. <br/> The [docs](https://docs.platforme.com/#config-endpoints-info) are outdated. <br/> Used `_params` to avoid collision with `params` which means a different thing (request params rather than a param named `params`) |
=> Add missing params to configInfo

src/js/visual/configurator-prc.js, src/js/visual/image.js
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-sdk-components-vue/issues/45 |
| Decisions | Due to the async nature of the configurator and image execution, it is possible to initiate the destruction of a component that uses the configurator and images while they are updating their state. This would result in the `DOM element` not existing anymore and the components would try to access them, resulting in errors. The solution was returning the functions if the `element` was not defined.  |
| Animated GIF | Showing no errors when initiating and destroying components rapidly: ![destroy_configurator](https://user-images.githubusercontent.com/25725586/102105304-26c4a400-3e27-11eb-8e21-fa8806e57ef8.gif)|
=> #45: Configurator error on destroy

src/js/api/availability-rule.js, src/js/api/brand.js, src/js/api/country-group.js, src/js/api/letter-rule.js, src/js/api/notify-info.js, src/js/api/price-rule.js, src/js/base/logic.js, src/js/base/ripe.js
| - | - |
| --- | --- |
| Issue | -- |
| Decisions | While doing methods for the new SKU endpoints, I noticed several inconsistencies in the documentation. Missing periods, `id` in lowercase, capitalized entities and duplicated lines. |
=> docs: fix inconsistencies

src/js/visual/configurator-prc.js, src/js/visual/image.js
| - | - |
| --- | --- |
| Issue | Originated from https://github.com/ripe-tech/ripe-twitch-ui/pull/54 (read description) |
| Decisions | From what I understood, the configuration cancel operation proceeds if the signatures don't match, since this means that there is an update process happening. However, the signature assignment was happening earlier in the update process and, when trying to cancel it would not work, since the signatures would match, even with the `_loadFrame` and preload happening. <br><br>By moving the signature assignment below, the signatures will only match when all promises are finished, and the cancel operation will successfully be performed when the `_preload` action is in the process (by running the `_finalize`).<br><br> The reasoning behind …
=> fix: configurator cancel signature error

src/js/base/api.js, test/js/base/api.js
| - | - |
| --- | --- |
| Issue | Originated from https://github.com/ripe-tech/ripe-twitch-ui/pull/71 |
| Decisions | The twitch ui uses only initialsExtra to save the initials state. This caused problems when using an URL with only one group in the initials extra field. <br> The `_parseExtraS` function does not support extraS to be a string. However this can happen if the `initials_extra` in the URL comes with only one group, and the `_unpackQuery` function returns the initials_extra as string instead of an array. <br> This caused errors in the parsing, where instead of returning a correct `initialsExtra` object, it returned an object parsed by each letter. <br><br> Based on the previous PR (https://github.com/ripe-tech/ripe-sdk/pull/237#issuecomment-770874298), the …
=> fix: support initialsExtra with one group in _queryToSpec

types/api/order.d.ts, types/base/api.d.ts
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-twitch/issues/36 |
| Dependencies |--|
| Decisions | Add types and export `getPriceP` |
=> #36: Export and add types to `getPriceP`

src/js/base/struct.js
| - | - |
| --- | --- |
| Issue | Related to `juice` problem in PR https://github.com/ripe-tech/epir-papyrus/pull/86 |
| Decisions | `FileTuple` prototype assignment was also changing the `Array` prototype https://github.com/ripe-tech/ripe-sdk/blob/3096ffb0c7b9ce341f772e8fab974f3bad64ea12/src/js/base/struct.js#L18 which is used by `cheerio`, a `juice` dependency. This was causing weird behaviour in `juice`, resulting in a fatal error. <br> The solution was using Javascript's [`Object.create`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/create). |
| Animated GIF | **Before fix** `Array.prototype` before and after FileTuple prototype assigment: <br>![image](https://user-images.githubusercontent.com/25725586/107509717-d5bcfc00- …
=> fix: FileTuple prototype fix

test/js/base/struct.js
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-sdk/pull/241#issuecomment-776772209 |
| Decisions | Unit test that checks that the Array constructor was not overridden by FileTuple. |
=> test: verify that the array constructor is not overriden by FileTuple

src/js/visual/configurator-prc.js
| - | - |
| --- | --- |
| Issue | Related to https://github.com/ripe-tech/ripe-twitch-ui/pull/88 |
| Decisions | When destroying rapidly the configurator, the `_drawMask` function can still be called if caught between the 150 timeout in https://github.com/ripe-tech/ripe-sdk/blob/4a237e48530b57efd9171cdffd6ad7492f2b6be4/src/js/visual/configurator-prc.js#L1178-L1188 <br> This resulted in a console error, but otherwise did not impact the functioning of anything. <br> The fix is similar to the ones applied in other places. |
=> fix: check if element is not defined in drawMask

src/js/visual/configurator-prc.js
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-white/issues/650 |
| Decisions | **Problem:** When customizing and then clicking in another part, the `changeFrame` call was being executed when the `configurator` was still `preloading`, resulting in the change frame operation being ignored an never executed: https://github.com/ripe-tech/ripe-sdk/blob/dd48403c58cf4f30d091f28cdc9425fd66de7b9a/src/js/visual/configurator-prc.js#L432-L434 <br>**Solution**: Save the operation in an array of pending operations to be executed later when the preloading promise ends. This needs to also happen when the preload is cancelled, since it would result in lost alterations when doing several customizations. |
| Animated GIF | …
=> #650: Save and later execute changeFrame operations while preloading

src/js/api/order.js
| - | - |
| --- | --- |
| Decisions | Add missing fields. Some of them for `buildless` orders, some of them for usual orders. Sorted based on [order](https://github.com/ripe-tech/ripe-core/blob/master/src/ripe_core/models/order.py) fields |
=> feat: add import order fields

src/js/base/ripe.js, src/js/visual/configurator-prc.js
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-white/issues/641#issuecomment-780589887 |
| Decisions | This bug was introduced at a [refactor](https://github.com/ripe-tech/ripe-white/commit/53473e502528c44efd547b90bf039c7a06267db3#diff-b671d69de830c33eb2f46a7ef178954ff04079bb2baaa93fa568759b45781accR132) after the [fix](https://github.com/ripe-tech/ripe-white/pull/643). This regression exposes an unexpected RIPE SDK behavior - when we do `setInitialsExtra` it sets `ripe.initialsExtra` but not `ripe.options.initialsExtra`. <br><br>On the other hand `config()` sets both `ripe.initialsExtra` and `ripe.options.initialsExtra`, that's why it was working before the refactor when we were doing everything in `config()`.<br><br>Now RIPE White uses `$ripe.initials`, …
=> #641 Fix setting initialsExtra in root and options of ripe instance

types/base/api.d.ts
| - | - |
| --- | --- |
| Issue | Necessary for `twitch` `nativeToSizeP` call in future fix for sizes. |
| Decisions | Typings for `nativeToSizeP` method. |
=> feat: nativeToSizeP typings

src/js/base/ripe.js
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-white/issues/825 |
| Decisions | Add missing `variant` to `_getState` return object so variant isn't ignored when doing [_update](https://github.com/ripe-tech/ripe-sdk/blob/master/src/js/base/ripe.js#L1287) as it is clearly needed later on when [getPriceP](https://github.com/ripe-tech/ripe-sdk/blob/master/src/js/base/ripe.js#L1314) is called. This is a dependency for a [higher level fix in ripe-commons-pluginus](https://github.com/ripe-tech/ripe-commons-pluginus/pull/237).   |
=> #845 Fix missing variant in _getState

src/js/base/compat.js
| - | - |
| --- | --- |
| Issue | In `epir-papryus` an error occurred when running the deployed version, when the SDK initialization was made. This was due to the fact that `fetch` was not defined: <br>![image](https://user-images.githubusercontent.com/25725586/117636788-0e0fae80-b179-11eb-8c20-ac21067a3ff6.png) |
| Decisions | Locally this works, but when running `nuxt --standalone`, the `global.fetch` is not defined. After some exploration, the variable `VUE_SSR_CONTEXT` is defined as an empty object in `global` when running nuxt as standalone. |
=> feat: use node-fetch when global.fetch is not defined

src/js/base/ripe.js
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-compose/issues/84 |
| Decisions | Initializes `initialsBuilder` with the local implementation, so that if `useInitialsBuilderLogic` is false, it still has it defined. There was a problem that I did not notice (my mistake) with the calls made inside `initialsBuilder`, which needed to be inside the owner `context`. |
=> #84: fix initials builder calls

CHANGELOG.md, src/js/api/order.js
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-pulse/issues/219 |
| Decisions | Add `rejectOrderP` and `rejectOrder` methods |
=> #219 Adds rejectOrder and rejectOrderP methods

CHANGELOG.md, src/js/api/order.js
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-pulse/issues/211 |
| Dependencies | https://github.com/ripe-tech/ripe-core/pull/4571 |
| Decisions | Add API endpoint for order to force creation of the waybill. |
=> feat: create waybill for order

CHANGELOG.md, src/js/api/order.js
| - | - |
| --- | --- |
| Issue | -- |
| Decisions | Other option values passed (for example `justification`) were not being propagated as expected to `setOrderStatus`. |
=> Fix: Override tracking info and keep other params 

CHANGELOG.md, src/js/api/order.js
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-pulse/issues/230 |
=> fix: stateCreateAttachmentOrder regression

src/js/base/ripe.js, test/js/base/ripe.js
| - | - |
| --- | --- |
| Issue | Originated from @joao-conde ripe-green component which was setting no context. |
| Decisions | If no context is provided (null), the profile building should still be made. This PR fixes that. |
=> fix: support null context on buildProfiles function

CHANGELOG.md, gulpfile.js
| - | - |
| --- | --- |
| Issue | Itertools methods were not present in the build file. Bug found in ripe-green. This one was fun to debug 🔪 🙃 |
| Animated GIF | |
=> fix: add itertools file to basefiles

src/js/base/compat.js, src/js/visual/image.js, test/js/visual.js
| - | - |
| --- | --- |
| Issue | -- |
| Decisions | **What is happening?**<br>In the specific case of the test, without setting the default values, there are two different requests: the first has the URL without initials and sets the `_loadedCallback` to its callback when it loads. However, when the second requests comes, it has a different URL and overrides the loadedCallback, never allowing the first request to finish. <br>It's necessary to cancel the previous request before making a new one.|
| Animated GIF | Before:<br><img width="550" alt="image" src="https://user-images.githubusercontent.com/25725586/130098589-67ee338c-03e6-4ccf-a864-1ee7536150db.png"><br>Now:<br><img width="212" alt="image" src="https://user-images.githubusercontent.com/25725586/130098962-a34c …
=> fix: sets default values for initials and engraving on image update

CHANGELOG.md, src/js/visual/configurator-prc.js
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-sdk/issues/307 |
| Decisions | Checks if build contains `no_masks` tag and disables the masks in the configurator. It takes precendence over the options passed to the configurator. |
https://user-images.githubusercontent.com/25725586/131869488-8a8b28b1-1106-4a49-9cec-606c02118a6a.mp4
=> #307: Disable masks if build contains "no_masks" tag

src/js/visual/configurator-prc.js
| - | - |
| --- | --- |
| Issue | ConfigAnimate was not being used anywhere, making it impossible to disable the animation when first starting the configurator. (The last usage of configAnimate: https://github.com/ripe-tech/ripe-sdk/commit/eae86f176455956d5001d38747c2e579145b52d8#diff-44149027047186f90ca764a3b50eacce3ee815a9f66e73889332689a453b85bd) |
| Decisions | - In the configurator `update` method, checks if no signature exists before (meaning that it's a new config), if that is the case, it uses the configAnimate to set the animation (if defined). |
| Animated GIF | **Before:**![green-config-before](https://user-images.githubusercontent.com/25725586/137885340-5d7e7b2d-847c-4961-affd-c10e5c677343.gif)<br>**Now:**<br>![Kapture 2021-10-19 at 10 39 …
=> feat: use config animate if update is made after config

CHANGELOG.md, src/js/base/api.js
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-sdk/issues/312 |
| Decisions | - Support `size` param in mask image request `_getMaskURL` (ripe-white is already passing this parameter). |
| Animated GIF | Before:<br><img width="2559" alt="image" src="https://user-images.githubusercontent.com/25725586/139242069-6b6e822d-f338-4302-a081-8954ef4cd584.png"><br>Now:<br><img width="2560" alt="image" src="https://user-images.githubusercontent.com/25725586/139241720-d50f50ad-8840-4ce2-9ab6-8c43b7aca43b.png">|
=> #312: Suport size in mask image request

CHANGELOG.md, src/js/api/order.js
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-pulse/issues/263 |
| Dependencies | https://github.com/ripe-tech/ripe-core/pull/4630 |
| Decisions | - Added `blockOrderP` method to block and order (status `blocked`). |
=> #263: `blockOrderP` to block an order

CHANGELOG.md, src/js/api/order.js
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/peri-shipping/issues/29 |
| Dependencies | https://github.com/ripe-tech/ripe-core/pull/4631 |
| Decisions | Replicate `setTracking` logic but for return tracking info. |
=> feat: add `setReturnTracking`

CHANGELOG.md, src/js/api/order.js
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/peri-shipping/issues/29 |
| Dependencies | https://github.com/ripe-tech/ripe-core/pull/4627 |
| Decisions | Add a `createReturnWaybillOrder` method. |
=> feat: create return waybill method

CHANGELOG.md, src/js/api/order.js
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/peri-shipping/issues/34 |
| Decisions | Add `setProofOfDeliveryP` and `setProofOfDelivery` methods |
=> feat: `setProofOfDelivery`  method

test/js/api/brand.js
| - | - |
| --- | --- |
| Issue | Failing `getLogoP` test that changed the value size of the image returned:<br>
=> test: fix brand getLogoP test

src/js/api/order.js
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-sdk/pull/329/files/c11f261d7d5d3b9ccf74aaefe4379967c2fbed28#r758316960 |
| Decisions | Added missing documentation for order methods. |
=> docs: add missing order methods documentation

CHANGELOG.md, src/js/api/size.js, test/js/api/size.js
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-core/issues/4638 |
| Decisions | • Add `localeToNative`, `localeToNativeP`, `localeToNativeB ` and `localeToNativeBP` methodsto convert locale sizes to native sizes<br>• Add `#localeToNative()` and `#localeToNativeB()` tests  |
| Tests | ![imagem](https://user-images.githubusercontent.com/22588915/142650747-75d3f0d1-a531-43ba-9185-09a045736236.png) |
=> #4638 Locale size to native size

CHANGELOG.md, src/js/visual/configurator-prc.js
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-white/issues/943 |
| Decisions | Support rectangle images in configurator |
**Test: use context `saint_laurent_hoodie`** 
https://user-images.githubusercontent.com/25725586/148554763-27ddc8f5-3e3d-4c3e-bc27-327445d1ad14.mp4
=> #943: configurator PRC support for width and height (non-square images)

CHANGELOG.md, src/js/visual/configurator-prc.js, src/js/visual/image.js
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-white/issues/948 |
| Animated GIF | Comparison (left is sbx): ![image](https://user-images.githubusercontent.com/25725586/149177875-e5b77ad1-a639-4d94-adf2-817863c99140.png)|
=> #948: Use pixel ratio in image

CHANGELOG.md, src/js/visual/image.js
| - | - |
| --- | --- |
| Issue | In computers with non-int pixel ratio, this occured (width is float):<br><img width="1345" alt="imagem" src="https://user-images.githubusercontent.com/25725586/149817293-f04312cd-a62c-407a-8992-20ad3d3bc668.png"><br><img width="1165" alt="imagem" src="https://user-images.githubusercontent.com/25725586/149817360-e7dc86ba-752b-4056-b238-2c00f2a841a0.png"> |
| Decisions | - Convert image `size` and `width` and `height` to ints, since compose only supports ints. |
=> fix: convert image size and width height to ints

src/js/visual/configurator-prc.js, src/js/visual/image.js
| - | - |
| --- | --- |
| Issue | `usePixelRatio` was in configurator instead of image (my bad) |
=> fix: move usePixelRatio logic to image instead of configurator

CHANGELOG.md, src/js/visual/configurator-prc.js
| - | - |
| --- | --- |
| Issue | Since the width and height are set has default, it did not defaulted to the clientWidth (space available) of the configurator element, which caused regressions on ripe-green:<br>![imagem](https://user-images.githubusercontent.com/25725586/149818458-39d21c29-7c64-4db4-a4c9-ee20a16f0589.png)<br>https://github.com/ripe-tech/ripe-green/pull/113#issuecomment-1014477503 |
| Decisions | - Remove default width and height of the configurator. |
| Animated GIF | Now:<br><img width="950" alt="imagem" src="https://user-images.githubusercontent.com/25725586/149818811-5a0e7664-7f72-4e35-ae72-98959393fa5a.png">|
=> fix: remove default width and height for configurator

CHANGELOG.md, src/js/api/brand.js
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/3db/issues/195 |
| Decisions | - Added `lineBreakP` and `lineBreak` methods to get the lines of text after line breaking logic is applied  - required for initials builder JS |
=> feat: line break endpoint API methods

CHANGELOG.md, src/js/api/order.js
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/peri-shipping/issues/33 |
| Decisions | Method(s) to update an order pickup reference number. |
=> feat: setPickupNumber for Order API

CHANGELOG.md, src/js/api/invoice-rule.js
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-pulse/issues/291<br>In peri-invoicing it is necessary to get a invoice rule for a specific brand, model and country. The endpoint to list available from the SDK does not allow very complex queries, so the need for this new endpoint. Using list endpoint - https://ripe-core-sbx.platforme.com/api/invoice_rules?filter_operator=$or&filters=brand:eq:swear&filters=shoe:eq:regent&filters=country:eq:PT- the wanted rule would be the second one. |
| Dependencies | https://github.com/ripe-tech/ripe-core/pull/4675 |
| Decisions |  - Resolve invoice rule function. |
=> feat: resolve invoice rule function

package.json, src/js/api/order.js
| - | - |
| --- | --- |
| Issue | Related to https://github.com/ripe-tech/ripe-sdk/pull/360 |
| Decisions | - In the linting setup in `gulpfile`, only the `src/js` files are being analyzed. In prettier the `js` files inside `src/python` were also being analyzed, which caused changes that do not reflect our linting standards to be made each time we ran `yarn pretty`. -> The same logic present in `gulpfile` was applied to prettier. If we made the contrary, several changes would need to be made to make `src/python/ripe_demo/static/js/main.js` compliant to our linting standards. |
=> fix: use same linting directories for prettier

CHANGELOG.md, src/js/api/order.js
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-util-vue/issues/247 |
| Decisions | A new invoicing field will be added to `ripe-util-vue`, and in order to correctly import the information inside of `ripe-pulse`, that information needs to be given in a specific format. In order to ensure consistency with `shippingInfo`, the new `invoicingInfo` field is now parsed on the SDK side. |
| Screenshots | <img width="1310" alt="image" src="https://user-images.githubusercontent.com/22790704/156210606-592e0fe0-ae48-428f-a000-80601188ffbb.png"> This was taken on an order created using `ripe-util-vue`, with a linked `ripe-sdk` to the version of this commit. |
=> Added suport for invoicing info

CHANGELOG.md, src/js/visual/configurator-prc.js
| - | - |
| --- | --- |
| Issue | Two problems<br>- `pixelRatio` was not being applied<br>- Was using the container size for the image instead of a locked one, which resulted in pixelated images when switching from mobile to desktop<br> |![white-resize-prob](https://user-images.githubusercontent.com/25725586/155129921-696db859-5b11-4c03-8509-5acf48e02232.gif) | Dependencies | -- |
| Decisions | - By **default**, use a locked dimension for the configurator - the default of the current face, which is obtained with `this.owner.getSize("$base", <current face>)`. This can be changed by setting the configurator variable `useDefaultSize` to `false`.<br>- Applies `pixelRatio` to the images downloaded for the configurator and does not allow its size to exceed the maximum for that face - with the …
=> fix: use locked dimensions for configurator (the face default) and apply DPR

CHANGELOG.md, src/js/api/sku.js
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-white/issues/979 |
| Dependencies | https://github.com/ripe-tech/ripe-core/pull/4698 |
| Decisions | - Add methods `getSkusCsvP` and `countSkusP` that return a CSV containing SKU and the number of documents, respectively |
=> #979: Methods `getSkusCsvP` and `countSkusP`

CHANGELOG.md, src/js/api/bulk-order.js
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-pulse/issues/281 |
| Decisions | Brand is optional so should not be used in the payload by default. |
=> fix: optional brand in payload

CHANGELOG.md, src/js/api/invoice-rule.js, src/js/api/transport-rule.js
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-core/issues/4703 |
| Dependencies | https://github.com/ripe-tech/ripe-core/pull/4707 |
| Decisions | - Adapt ripe-sdk methods to new size dimensions in rules. <br> - Add missing resolveTransportRule and resolveTransportRuleP methods.  |
=> #4703 Add size to rules

CHANGELOG.md, src/js/base/api.js
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-white/issues/996 |
| Dependencies | https://github.com/ripe-tech/ripe-core/pull/4710 |
| Decisions | - Methods `getVideoP` and `getVideoThumbnailP` that return a video and video thumbnail of a customization<br>- Methods `_getVideoURL` and `_getVideoThumbnailURL` that build the URL for accessing the video and image thumbnail - like `getImageURL`.  |
| Animated GIF | Below |
https://user-images.githubusercontent.com/25725586/159502592-c9097962-8f4b-4efd-9388-129398494e2a.mp4
https://user-images.githubusercontent.com/25725586/159502626-bcfff4e5-2d40-4fac-91a9-e8970cf8ccfc.mp4
=> #966: Methods to return a video and video thumbnail image

CHANGELOG.md, src/js/base/logic.js, src/js/base/ripe.js, src/js/visual/image.js
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-white/issues/996 |
| Dependencies | https://github.com/ripe-tech/ripe-core/pull/4710 |
| Decisions | - Added support in `image.js` for external image URL providers and frame validators. With this, the thumbnail component just needs to make `bindImage´ with the correct provider and SDK deals with the rest (update parts, change frame, etc)  |
| Animated GIF | Below |
https://user-images.githubusercontent.com/25725586/159502592-c9097962-8f4b-4efd-9388-129398494e2a.mp4
https://user-images.githubusercontent.com/25725586/159502626-bcfff4e5-2d40-4fac-91a9-e8970cf8ccfc.mp4
=> #966: Image support for external image providers/frame validators

CHANGELOG.md, src/js/base/ripe.js
| - | - |
| --- | --- |
| Issue | Happening in https://ripe-white-now.platforme.com/?brand=unspun&model=cozy_wide ![image](https://user-images.githubusercontent.com/25725586/160116609-fe45ba20-191a-4de2-b765-98dea5c99606.png) |
| Decisions | - Unspun build does not have faces in the dimension in spec, added conditional for that |
=> fix: no faces in dimension spec in `getDimension`

CHANGELOG.md, src/js/api/order.js, test/js/api/order.js
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-sdk/issues/381 |
| Decisions | Fixed methods `_getOrderReportURL`, `_getOrderReportPDFURL`, `_getOrderReportPNGURL` and their tests |
=> #381 Fix `_getOrderReportURL`, `_getOrderReportPDFURL`, `_getOrderReportPNGURL` logic and tests

CHANGELOG.md, src/js/base/ripe.js, src/js/visual/image.js
| - | - |
| --- | --- |
| Decisions | - Add `remoteInitialsBuilderLogic` and `noAwaitLayout` options. <br> - Adapt to not use initials builder in the client side and the cancellation logic to allow for faster response times. |
=> YSL: Add `remoteInitialsBuilderLogic` option

CHANGELOG.md, src/js/base/api.js, src/js/visual/image.js
| - | - |
| --- | --- |
| Decisions | - Add missing option for composition `composeOptions` to be passed in the URL. This will allow us to do things like `options: ["locale:zh_cn"]` when doing bindImage. |
=> YSL: Passing compose `options` option

CHANGELOG.md, package.json, src/js/base/ripe.js
This fixes an npmjs error for duplicated tag that was created before the release of 2.27.0 and the deployment failed with the message `You cannot publish over the previously published versions: 2.27.0.`
Here's the workflow with the error of the deployment https://github.com/ripe-tech/ripe-sdk/runs/6062181012?check_suite_focus=true
Note: I had to remove the tag 2.27.0 as it was being problematic
=> version: 2.28.0

CHANGELOG.md, src/js/base/struct.js, test/js/base/struct.js
| - | - |
| --- | --- |
| Issue | Port from https://github.com/hivesolutions/yonius/pull/39 (related to https://github.com/ripe-tech/hermes-proxy/issues/135) |
| Decisions | • Add `fromArrayBuffer` and `fromBlob` to `FileTuple`<br>• Add tests: `#fromString()`, `#fromArrayBuffer()` and `#fromBlob()` |
=> #135 Add `fromArrayBuffer` and `fromBlob` to `FileTuple`

CHANGELOG.md, src/js/visual/image.js
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-white/issues/978 |
| Decisions | - Support for profile overriding on image - it should be possible to override the profiles, this is useful for showing personalization frames that are defined by thumbnails - see https://github.com/ripe-tech/ripe-docs/pull/618 |
=> #978: support profile overriding in image

CHANGELOG.md, package.json, src/js/base/ripe.js
* Add `fromArrayBuffer` and `fromBlob` to `FileTuple` - [hermes-proxy/135](https://github.com/ripe-tech/hermes-proxy/issues/135)
* Added `safe` param to be passed in `importOrder` - [ripe-util-vue/#259](https://github.com/ripe-tech/ripe-util-vue/issues/259)
* Support profile overriding in image - [ripe-white/#978](https://github.com/ripe-tech/ripe-white/issues/978)
=> version: 2.30.0

CHANGELOG.md, src/js/api/order.js
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-robin-revamp/issues/363 |
| Dependencies | https://github.com/ripe-tech/ripe-core/pull/4740 |
| Decisions | -  Add param `tenant_id` to `updateTagOrder` method |
=> #363 Tag: Add param `tenent_id`

CHANGELOG.md, src/js/api/order.js, test/js/api/order.js
| - | - |
| --- | --- |
| Issue | -- |
| Decisions | Contents filled only if there are values. If there are none, dont send an object with null values. Pass DKU if it exists. Add a size to import order.<br> Passing no size, previously, we had a contents like `{ size: null }` and this does not fail when importing. Meaning there is some bug in Core, to be fixed in another PR. |
=> fix: import order DKU

CHANGELOG.md, src/js/api/brand.js
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-core/issues/4745 |
| Decisions | - Add new `variant` and `size` params to `_getConfigOptions` method |
=> #4745 Add `variant` and `size` params to `_getConfigOptions`

CHANGELOG.md, README.md
| - | - |
| --- | --- |
| Issue | If the user doesn't add the CSS `link` the configurator won't work properly |
| Decisions | Document how to include the CSS link |
Issue:
https://user-images.githubusercontent.com/22588915/187227122-b49b9add-96ec-43e6-aa8a-0470e3a8e0c4.mp4
=> Dcoument required CSS `link` for configurator to work properly

CHANGELOG.md, src/python/ripe_demo/static/js/main.js
| - | - |
| --- | --- |
| Issue | There are linter warnings in ripe-sdk-demo .js files |
| Decisions | Avoid warnings by not using `var` in ripe-sdk-demo .js files |
=> Don't use `var` in ripe-sdk-demo

CHANGELOG.md, src/js/base/config.js, src/js/base/ripe.js
| - | - |
| --- | --- |
| Issue | -- |
| Decisions | Add the method `hasStrategy` which checks if a build has a specific strategy. It does that by checking the config `strategies` array values for a match. If a build doesn't have `strategies` variable it will check against "prc" as it's our default strategy |
=> Add `hasStrategy` method

CHANGELOG.md, src/js/visual/configurator-csr.js
| - | - |
| --- | --- |
| Issue | By default the renderer uses linear encoding. Changing to `sRGBEncoding` will improve the mesh color accuracy |
| Decisions | Set renderer output encoding to `sRGBEncoding` by default |
=> Set renderer output encoding to `sRGBEncoding`

CHANGELOG.md, src/js/visual/configurator-csr.js
| - | - |
| --- | --- |
| Issue | CSR loading time has a lot of room for improvements |
| Dependencies | https://github.com/ripe-tech/ripe-sdk/pull/414 |
| Decisions | Paralellize CSR scene resource loading operations thus greatly decreasing loading times. From my quick tests it went from an avg. of 2209ms to 1346ms (863ms difference) |
=> Greatly improve CSR scene loading time

CHANGELOG.md, src/python/ripe_demo/static/js/main.js
| - | - |
| --- | --- |
| Issue | Forgot to hide the CSR configurator on the start of the demo |
| Decisions | Hide CSR configurator at the demo start |
=> Fix CSR configurator no being hidden at the demo start

CHANGELOG.md, src/js/visual/configurator-csr.js
| - | - |
| --- | --- |
| Issue | Forgot to add override support for CSR camera transforms |
| Decisions | Allow override of CSR camera transforms on init |
=> Fix not being able to override camera transforms on init

CHANGELOG.md, src/js/visual/configurator-csr.js
| - | - |
| --- | --- |
| Decisions | When syncing from PRC, it now also resets the camera zoom |
=> Reset CSR configurator zoom on PRC sync

CHANGELOG.md, src/js/visual/configurator-csr.js
| - | - |
| --- | --- |
| Decisions | Fixed issue where CSR debug tools wouldn't initialize if the CSR initials were enabled and the CSR initials points array had no points |
=> Fix CSR debug mode not properly initializing when no CSR initials points are set

CHANGELOG.md, gulpfile.js, src/js/visual/configurator-csr.js, src/js/visual/csr/utils.js
| - | - |
| --- | --- |
| Decisions | - Remove external draco loader files dependency by including draco loader with the bundle<br>- Add `loadGLTF()` method to utils |
=> #429 Remove external draco loader dependency

.github/workflows/main.yml, CHANGELOG.md, gulpfile.js, package.json
| - | - |
| --- | --- |
| Issue | -- |
| Dependencies | Added https://www.npmjs.com/package/gulp-shell and https://www.npmjs.com/package/nyc to run test coverage. Other gulp packages like gulp-istanbul are poorly maintained, not downloaded or used enough. |
| Decisions | Add test-coverage script. |
=> test: add coverage

CHANGELOG.md, src/js/visual/configurator-csr.js
| - | - |
| --- | --- |
| Decisions | Support tone mapping (the default is ACES Filmic tonemapping)  |
**None:**
**Linear:**
**ACES Filmic:**
**Reinhard:**
**Cineon:**
=> #429 [CSR] Add tone mapping

CHANGELOG.md, src/js/visual/configurator-csr.js
| - | - |
| --- | --- |
| Decisions | Fix CSR debug line points boxes wrong size  |
**Before:**
https://user-images.githubusercontent.com/22588915/198253206-71997f8c-16bb-46d2-b5b0-34aea0c65763.mp4
**After:**
https://user-images.githubusercontent.com/22588915/198253215-a326cbb1-7e58-427d-b7af-629eb438a0a2.mp4
=> #429 [CSR] Fix debug line points boxes wrong size

CHANGELOG.md, src/js/visual/csr/utils.js
| - | - |
| --- | --- |
| Decisions | - Add `toXYZObject()` util. It is used to convert array of coordinates to {x, y, z} object.<br>- Add `toVector3()` util. It is used to convert array/object of coordinates to a Three.js Vector3 value.<br>- Add `toToneMappingValue()` util. It is used to convert a tone mapping string key to it's respective Three.js Value. |
=> #429 Add `toXYZObject`, `toVector3` and `toToneMappingValue` utils

CHANGELOG.md, src/js/visual/configurator-csr.js, src/js/visual/csr/rendered-initials.js
| - | - |
| --- | --- |
| Decisions |  Increase number of curve types supported by `CsrRenderedInitials`. The types supported are `centripetal`, `chordal` and `catmullrom` which are part of the family of Catmull–Rom splines. |
**`catmullrom` type with `tension = 0` example:**
**`catmullrom` type with `tension = 1` example:**
**`chordal` type example:**
**`chordal` type example:**
=> #429 Increase number of curve types supported by `CsrRenderedInitials`

CHANGELOG.md, package.json
* Add new `variant` and `size` params to `_getConfigOptions` method - [ripe-core/#4745](https://github.com/ripe-tech/ripe-core/issues/4745)
* Add `variant` passing through `onConfig` and `onPart` - [#429](https://github.com/ripe-tech/ripe-sdk/issues/429)
* Add CSS `link` to `README.md`
* Add `hasStrategy` method - [#429](https://github.com/ripe-tech/ripe-sdk/issues/429)
* Add `CsrAnimation`, `CsrChangeFrameAnimation` and `CsrUtils` - [#429](https://github.com/ripe-tech/ripe-sdk/issues/429)
* Add `changeFrame` and `flushPending` methods to CSR configurator - [#429](https://github.com/ripe-tech/ripe-sdk/issues/429)
* Add click binds to ripe-sdk-demo that allows to match CSR to the PRC frames - [#429](https://github.com/ripe-tech/ripe-sdk/issues/429)
* Add `syncFromCSR` method to …
=> version: 2.32.0

CHANGELOG.md, src/js/visual/configurator-prc.js
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-sdk/issues/446 |
| Decisions | If masks are not to be used, just avoid loading them but create the buffers anyways. |
| Animated GIF | **Before**<br> ![image](https://user-images.githubusercontent.com/16060539/203519409-ffcafdfb-3ca0-48ab-9193-e290f34f0787.png) **After**<br>  ![image](https://user-images.githubusercontent.com/16060539/203519673-bbc916f4-ec15-4746-9349-9f0515870867.png)|
For example, using the following test script:
```js
configuratorPrc = ripe.bindConfigurator(element, {
duration: 250,
useMasks: true,
view: bestFace(result)
});
configuratorPrc.isFirst = true;
setTimeout(() => {
configuratorPrc.updateOptions({ useMasks: false });
}, 6000);
```
I was able to start out with masks and 6 …
=> fix: load mask only if using masks

CHANGELOG.md, src/js/api/order.js, test/js/api/order.js
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-pulse/issues/271 |
| Decisions | - Add `quantity` param to `_importOrder` method |
=> #271 Add quantity param to import order

CHANGELOG.md, src/js/visual/configurator-csr.js
| - | - |
| --- | --- |
| Dependencies | https://github.com/ripe-tech/ripe-docs/pull/631 |
| Decisions |  Improved manipulation of initials canvas curvature by supporting loading `curve_type` and `curve_tension` from config. Related: https://github.com/ripe-tech/ripe-sdk/pull/442 |
=> #429 Support `curve_type` and `curve_tension` config

CHANGELOG.md, src/js/visual/configurator-csr.js
| - | - |
| --- | --- |
| Decisions | Fix CSR initials control points debug boxes being too small |
| Screenshots | **Before:**<br>![image](https://user-images.githubusercontent.com/22588915/210245737-8c6f1c22-783f-4276-a880-58f974fd55f5.png)<br>**After:**![image](https://user-images.githubusercontent.com/22588915/210245064-e084ec2c-18c4-4500-83cb-3a1b44591feb.png) |
=> #429 Increase control points debug boxes size

CHANGELOG.md, package.json, src/js/base/ripe.js
* Support `curve_type` and `curve_tension` config values - [#429](https://github.com/ripe-tech/ripe-sdk/issues/429)
* Add `get3dSceneEnvironmentUrl`, `getInitials3dBaseTextureUrl` and `getInitials3dDisplacementTextureUrl` methods - [#429](https://github.com/ripe-tech/ripe-sdk/issues/429)
* Set CSR mesh url default variant value to `"$base"` - [#429](https://github.com/ripe-tech/ripe-sdk/issues/429)
* Use config in CSR - [#429](https://github.com/ripe-tech/ripe-sdk/issues/429)
* Change default test timeout to 60 seconds
* Revert ripe-sdk-demo variant value to `""` - [#429](https://github.com/ripe-tech/ripe-sdk/issues/429)
* If no masks are to be used, create the mask buffers but don't load them, avoiding network requests - [#446](https://github.com/ripe-tech/ripe-sdk/issues/446)
* Fix CSR …
=> version: 2.34.0

CHANGELOG.md, package.json, src/js/base/ripe.js
* Fix `stateChatLinesOrderP` reference method - [ripe-robin-revamp/#340](https://github.com/ripe-tech/ripe-robin-revamp/issues/340)
=> version 2.35.1 :rainbow: 

CHANGELOG.md, src/js/api/brand.js, src/js/visual/configurator-csr.js, src/js/visual/csr/rendered-initials.js
| - | - |
| --- | --- |
| Decisions | - Add `getTextureMapUrl` method<br>- Support metallic, normal and roughness textures<br>- Generalize `CsrRenderedInitials` textures logic |
=> #429 Support metallic, normal and roughness textures

CHANGELOG.md, src/js/visual/configurator-csr.js
| - | - |
| --- | --- |
| Decisions | Allows setting a callback to be ran immediately after the render. This is useful for cases where, for example, we want immediate access to the renderer frame buffer |
=> #429 Support post render callback

CHANGELOG.md, src/js/api/order.js, src/js/base/api.js, src/js/base/ripe.js
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-robin-revamp/issues/416 |
| Decisions | - Add `authCallback` to global options and improved overall behavior - returning the callback to allow one call authentication. |
=> #416 Auth callback

CHANGELOG.md, src/js/api/brand.js, src/js/visual/configurator-csr.js
| - | - |
| --- | --- |
| Decisions | Add `getInitialsConfig `, `getInitialsConfigP()` and `_getInitialsConfigOptions ()` methods<br> Load enriched initials config |
=> #429 Use enriched initials config

CHANGELOG.md, src/js/api/brand.js, src/js/visual/configurator-csr.js
| - | - |
| --- | --- |
| Dependencies | <del>https://github.com/ripe-tech/ripe-sdk/pull/455</del> |
| Decisions | Add `getFontUrl()` and `_getFontOptions()` methods<br> Load font based on config |
=> #429 Support loading of external fonts

CHANGELOG.md, gulpfile.js, src/js/visual/configurator-csr.js, src/js/visual/csr/utils.js
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-sdk/issues/481 |
| Decisions | - Fix meshes compressed with Draco not loading properly<br>- Improve performance by reusing Draco loader instance instead of loading it each time a mesh is loaded<br>- Removed `draco_decoder.js` dependency as it's not needed to be bundled anymore |
=> #481 Fix meshes compressed with Draco not loading properly

CHANGELOG.md, src/js/visual/configurator-csr.js, src/js/visual/configurator-prc.js
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-white/issues/1098 |
| Decisions | - Add params to `ready` event in configurator csr  and prc, allowing for any loaders to catch this event. This is because `ready` event is triggered in a lot of places and not specific enough to use as a loader bind. |
=> #1098 Add params to `ready` event in configurator csr and prc

CHANGELOG.md, src/js/base/config.js, test/js/base/config.js
| - | - |
| --- | --- |
| Issue |https://github.com/ripe-tech/ripe-sdk/issues/479 |
| Decisions | - Add initialsConfig() method which runs the appy profiles logic locally. It's a implementation that matches the one done here: https://github.com/ripe-tech/ripe-compose/blob/40436c5207b01fdff100e6d2425018feb453c731/src/ripe_compose/util/configurator.py#L2213. The reason it's done is to support a way to compute the initials with the profiles applicated without having to do a remote call<br>- Add `initialsConfig()` tests |
=> #479 Support computation of initials config by adding `initialsConfig` method

CHANGELOG.md, package.json, src/js/base/ripe.js
* Add `id` and `origin` to `ready` event params to distinguish events from configurator prc and csr - [ripe-white/#1098](https://github.com/ripe-tech/ripe-white/issues/1098)
* Add `initialsConfig` method - [#479](https://github.com/ripe-tech/ripe-sdk/issues/479)
* Add `#initialsConfig()` tests - [#479](https://github.com/ripe-tech/ripe-sdk/issues/479)
* Reuse Draco loader instance - [#481](https://github.com/ripe-tech/ripe-sdk/issues/481)
* Removed `draco_decoder.js` dependency - [#481](https://github.com/ripe-tech/ripe-sdk/issues/481)
* Use `initialsConfig()` in CSR - [#479](https://github.com/ripe-tech/ripe-sdk/issues/479)
* Fix meshes compressed with Draco not loading properly - [#481](https://github.com/ripe-tech/ripe-sdk/issues/481)
=> Version: `2.38.0`

CHANGELOG.md, package.json, src/js/base/ripe.js
* Allowing set initials extra of empty or single group initials in configurator csr - [ripe-white/#1098](https://github.com/ripe-tech/ripe-white/issues/1098)
=> version: 2.39.0 :rainbow: 

.gitignore, CHANGELOG.md, documentation/src/README.md
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-sdk/issues/478 |
| Decisions | - Fix div tag outside code block in CSR documentation <br> - Update `.gitignore` to ignore CSR documentation compilation files |
=> #478 Fix CSR documentation compilation

CHANGELOG.md, src/js/api/brand.js, src/js/visual/configurator-csr.js
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-sdk/issues/499 |
| Decisions | - Stop using hardcoded Dropbox link (which is associated with my PlatformE account) and use PlatformE CDN<br>- Load environment file specified in the config |
=> #499 Load environment file bases on config

.github/workflows/deploy.yml, .github/workflows/main.yml, .travis.yml, CHANGELOG.md
| - | - |
| --- | --- |
| Decisions | Upgrade outdated node engine workflows to not include outdated LTS versions https://endoflife.date/nodejs |
=> Upgrade node engine

CHANGELOG.md, package.json, src/js/base/ripe.js
* Add `browserify`, `esmify`, `babelify`, `vinyl-buffer` and `vinyl-source-stream` dev dependencies - [#491](https://github.com/ripe-tech/ripe-sdk/issues/491)
* Support ES Modules - [#491](https://github.com/ripe-tech/ripe-sdk/issues/491)
* Upgrade workflows's node engine version
* Reduced import hacks - [#491](https://github.com/ripe-tech/ripe-sdk/issues/491)
* Remove `__VERSION__` references - [#491](https://github.com/ripe-tech/ripe-sdk/issues/491)
* Remove `mark` script - [#491](https://github.com/ripe-tech/ripe-sdk/issues/491)
* Update Three.js version to `150.1` - [#491](https://github.com/ripe-tech/ripe-sdk/issues/491)
* Update `@babel/core` to `7.21.0` - [#491](https://github.com/ripe-tech/ripe-sdk/issues/491)
* Removed unused `gulp-babel`, `gulp-concat` and `gulp-replace` dev …
=> Version: `3.0.0`

CHANGELOG.md, src/js/visual/configurator-prc.js
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-sdk/issues/511|
| Decisions | There is a boolean to force the sdk to use the `width` and  `height` to be used on the rendering call `useDefaultSize`. However that variable would always have a `true` value regardless of what was sent.|
=> #511 Configurator ignoring size

CHANGELOG.md, test/js/base/api.js
| - | - |
| --- | --- |
| Issue | Tests are failing fairly frequently when running `_authCallback` this is because the API testing provider `https://httpbin.org/` is not very stable/reliable. We could improve this by switching to a more reliable alternative. |
| Decisions | - Change `httpbin` to `postman-echo` as a more "production-ready" and mature alternative. |
=> Replace API test provider from `httpbin` to `postman-echo`

src/python/ripe_demo/controllers/base.py, src/python/ripe_demo/static/js/main.js, src/python/ripe_demo/templates/partials/layout.html.tpl
- https://github.com/ripe-tech/products/issues/132
- https://github.com/ripe-tech/ripe-sdk/pull/517
- added `compose_url` GET parameter to the RIPE SDK demo page
- None
=> feat: add compose url option to the ripe-sdk demo

CHANGELOG.md, package.json, src/js/base/ripe.js
* Admin Event API module - [ripe-core/#4828](https://github.com/ripe-tech/ripe-core/issues/4828)
=> version: 3.2.0

CHANGELOG.md, src/js/api/shipment.js
- https://github.com/ripe-tech/ripe-core/issues/4853
=> feat: shipment attachment API

CHANGELOG.md, package.json, src/js/api/shipment.js, src/js/base/ripe.js
* Shipment API `refreshShippingShipment` and `createReturnWaybillShipment`
=> version: 3.3.2

CHANGELOG.md, src/js/api/shipment.js
- void waybill methods for shipments
=> feat: void waybills shipments
