- src/js/base/ripe.js
- src/js/ripe.js
- src/js/visual/configurator.js
- src/python/ripe_demo/static/js/ripe.js
Related to: https://github.com/ripe-tech/ripe-core/issues/2290
> SDK: new naming and options added

- README.md
Related to: https://github.com/ripe-tech/ripe-core/issues/2290
> SDK: documentation update

- README.md
Related to: https://github.com/ripe-tech/ripe-core/issues/2598
> SDK: Browser support documentation

- src/js/ripe.js
- src/js/visual/configurator.js
- src/python/ripe_demo/static/js/ripe.js
https://github.com/ripe-tech/ripe-core/issues/2870
Fixed a bug when programatically highlighting a part that is already loaded.
> fixed highlight bug

- src/js/ripe.js
- src/js/visual/configurator.js
https://github.com/ripe-tech/ripe-core/issues/3004
> fixed highlight bug when using changeFrame

- README.md
https://github.com/ripe-tech/ripe-core/issues/3738
> added authentication docs

- src/js/visual/image.js
- src/js/visual/visual.js
- src/js/visual/image.js
- src/js/visual/visual.js
> Updating documentation

- gulpfile.js
- jsdoc.json
- package.json
> Update jsdoc theme

- src/js/visual/configurator.js
https://recordit.co/1BY6SjN7Ip
> Rotate in shortest path

- src/js/visual/configurator.js
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-whites/issues/183|
| Decisions | Send an event on configurator lowlight|
| Animated GIF |   |
| Dependencies ||
| |  |
> Send event on configurator lowlight.

- src/js/base/ripe.js
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-white/issues/178 |
| Decisions | • Added `new_child` to know when a new child was added to ripe <br>• Added `pre_update` to know when the `update` method will start |
| Animated GIF | - |
> #178 Events

- src/js/visual/configurator.js
- src/python/ripe_demo/static/js/main.js
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-white/issues/178 |
| Decisions | Added `pre_frame` and `post_frame`events. |
| Animated GIF | - |
> #178: _loadMask and _loadFrame function events

- src/js/api/build.js
- src/python/ripe_demo/static/js/main.js
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-white/issues/250 |
| Dependencies | - |
| Decisions | - |
| Animated GIF | - |
> #254 3DB Build list

- src/js/api/build.js
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-white/issues/253 |
| Dependencies | https://github.com/ripe-tech/ripe-core/pull/4439 |
> #253: Build artifacts method

- src/js/api/brand.js
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-white/issues/349 |
| Decisions | Call methods from the logic file of a build |
| Animated GIF | |
> #349: onLogic enpoint

- test/js/api/notify-info.js
- test/js/api/order.js
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-sdk/issues/176 |
| Decisions | Add unit tests to subscription endpoints created for in https://github.com/ripe-tech/ripe-sdk/pull/172 |
> #176 Unit tests for subscription endpoints

- src/js/api/build.js
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-building/issues/504 |
| Decisions | Add method to retrieve locale model keys |
> #504 Add get locale model keys

- src/js/visual/image.js
| - | - |
| --- | --- |
| Issue | -- |
| Decisions | Method updateOptions for `Image`. |
> Image updateOptions

- src/js/visual/image.js
| - | - |
| --- | --- |
| Issue | -- |
| Decisions | Since `crop` is a boolean, it is necessary to make a different update logic. |
| Animated GIF | |
> Fix crop update

- src/js/visual/configurator.js
| - | - |
| --- | --- |
| Issue | -- |
| Decisions | Configurator updateOptions logic similar to Image, [origin](https://github.com/ripe-tech/ripe-sdk/pull/193#issuecomment-669086309).|
> Configurator updateOptions backport from Image

- src/js/base/ripe.js
- src/js/visual/configurator-prc.js
> Avoid extra network requests on initial updates

- src/js/api/brand.js
Group:
- https://github.com/ripe-tech/ripe-sdk/pull/209
- https://github.com/ripe-tech/ripe-core/pull/4494
- https://github.com/ripe-tech/ripe-compose/pull/99
> Add getMesh

- src/js/api/brand.js
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-sdk/pull/209#issuecomment-724596632 |
> getMeshUrl

- src/js/api/brand.js
- test/js/api/brand.js
| - | - |
| --- | --- |
| Issue | #211 |
| Decisions | getLogoP and getLogo methods |
> #211: getLogo and getLogoP methods

- src/js/visual/image.js
| - | - |
| --- | --- |
| Issue | -- |
| Decisions | Correct rotation initialization |
> Fixed rotation initialization

- src/js/base/api.js
- test/js/visual.js
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-sdk/pull/213#issuecomment-726264057 |
| Decisions | • Added `should generate the correct image URL` test <br>• Fixed bad URL when passing `offsets` and `curve` |
| Screenshot | ![imagem](https://user-images.githubusercontent.com/22588915/99099126-e082e780-25d1-11eb-8b92-4adb3cc587cd.png) |
> #172 Image options test

- src/js/api/availability-rule.js
- src/js/api/index.js
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-util/issues/67 |
| Decisions | Add availability rules method as requested by https://github.com/ripe-tech/ripe-util/issues/67#issuecomment-726074138 |
> #67 Add availability rules methods to access endpoints

- src/js/base/api.js
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-design/issues/172 |
| Decisions | Added missing `initials_inclusion `param|
> #172 Added missing params

- src/js/base/ripe.js
| - | - |
| --- | --- |
| Issue | -- |
> Switched isEmpty method call

- src/js/api/brand.js
| - | - |
| --- | --- |
| Issue | Originated from https://github.com/ripe-tech/ripe-api-docs/pull/36 |
| Decisions | Update links to docs. |
| Animated GIF | |
> Update links to docs

- src/js/api/brand.js
- test/js/api/brand.js
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-compose/issues/84 |
| Decisions | • Function to connect to the endpoint that returns the logic `js` script for the build.  |
> Brand getLogic endpoints

- src/js/api/brand.js
- src/js/base/api.js
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-white/issues/618 |
| Decisions | Add model validation method to validate model on purchase button. |
> #618 Add validate model method

- src/js/api/sku.js
- test/js/api/sku.js
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-white/issues/730 |
| Dependencies | https://github.com/ripe-tech/ripe-core/pull/4513 |
| Decisions | Methods for new [LCRUD SKU methods](https://github.com/ripe-tech/ripe-core/pull/4513). <br><br> Only missing the udpated documentation in `docs.platforme.com`. |
| Animated GIF |  ![image (1)](https://user-images.githubusercontent.com/25725586/104609883-6a573b80-567b-11eb-9886-9f6f556ea9d3.png)|
> #730: SKUs methods

- src/js/base/logic.js
- src/js/base/utils.js
- src/python/ripe_demo/static/js/main.js
- test/js/base/utils.js
| - | - |
| --- | --- |
| Decisions | Ported from https://github.com/ripe-tech/ripe-commons-pluginus/blob/986588ada4e104ac273ed9d7f35c0a1dca721203/js/locale/model-locale-resolver.js#L102 which in turn is based on https://github.com/ripe-tech/ripe-compose/blob/master/src/ripe_compose/util/interface.py#L510. |
> feat: localeModel

- src/js/base/config.js
- src/js/visual/configurator-prc.js
- test/js/base/config.js
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-white/issues/761 |
| Dependencies | https://github.com/ripe-tech/builds-static/pull/1105 |
| Decisions | Add `hasInitialsRadius` status and small test to affected and non affected model. |
> #761 Add initials no radius status and test

- src/js/api/brand.js
- src/js/api/config.js
- src/js/base/ripe.js
> #768 Add size to setOptions

- src/js/api/order.js
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-robin-revamp/issues/212 |
| Dependencies | https://github.com/ripe-tech/ripe-core/pull/4530 |
> feat: chat lines and attachments count endpoints

- src/js/api/sku.js
| - | - |
| --- | --- |
| Dependencies | https://github.com/ripe-tech/ripe-core/pull/4531 |
> feat: validate SKU endpoint

- src/js/api/build.js
| - | - |
| --- | --- |
| Issue |-- |
| Decisions | Came across this and thought the version was supposed to be passed and opened a PR with that fix. Turns out its the JSDocs that are wrong, so I closed that PR and opened this new one. |
> docs: remove unused param

- types/api/build.d.ts
- types/api/index.d.ts
- types/base/api.d.ts
| - | - |
| --- | --- |
| Issue | -- |
| Decisions | Related to https://github.com/ripe-tech/ripe-twitch/issues/89 where we need to get the available builds for a brand |
> Type getBuildP

- types/base/api.d.ts
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-twitch/issues/89 |
| Decisions | In case logged user has no brand associated, list all builds. Requires SDK typings for TS interop. A new patch release should be made with this. |
> Feat: type getBuildsP

- CHANGELOG.md
- src/js/api/account.js
| - | - |
| --- | --- |
| Dependencies | https://github.com/ripe-tech/ripe-core/pull/4546 |
> feat: tenancyAccountMe

- CHANGELOG.md
- src/js/api/index.js
- src/js/api/order.js
- src/js/api/transport-rule.js
| - | - |
| --- | --- |
| Dependencies | https://github.com/ripe-tech/ripe-core/pull/4549 |
> feat: transport endpoints

- CHANGELOG.md
- src/js/api/order.js
| - | - |
| --- | --- |
| Dependencies | https://github.com/ripe-tech/ripe-core/pull/4557 |
> feat: setTracking

- CHANGELOG.md
- src/js/api/order.js
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-core/issues/4558 |
> feat: set meta

- CHANGELOG.md
- src/js/api/order.js
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/peri-shipping/issues/5 |
| Dependencies | https://github.com/ripe-tech/ripe-core/pull/4566 |
> Feat: add shipping info to import order

- CHANGELOG.md
- src/js/api/order.js
- src/js/base/api.js
- test/js/base/api.js
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-sdk/issues/282 |
> feat: attachments meta and name

- CHANGELOG.md
- src/js/api/attachment.js
- src/js/api/index.js
- src/js/api/order.js
- src/js/base/api.js
- test/js/api/attachment.js
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-robin-revamp/pull/281#pullrequestreview-711609407 |
| Decisions | Add method to get an attachment URL given its key.|
> #105 Get attachment URL

- CHANGELOG.md
- package.json
- src/js/base/ripe.js
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-pulse/pull/232#issuecomment-886536023 |
> version: 2.2.2

- src/js/base/compat.js
| - | - |
| --- | --- |
| Issue | ripe-sdk doesn't work with react-native |
| Cause | https://github.com/ripe-tech/ripe-sdk/commit/7ea354fdb4708fed47289de60680ec1fd6af6925#diff-d476472347dfbf40dc14179ea9f4b484e68186d2bd3ebcdbd65a46d711dbcf88R113 |
> fix: requires to comply with react-native

- CHANGELOG.md
- src/js/visual/configurator-prc.js
> feat: use option size in configurator resize

- src/js/api/order.js
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/peri-shipping/issues/11 |
| Dependencies | https://github.com/ripe-tech/ripe-core/pull/4585 |
| Decisions | Endpoint for note creation for a given order. |
> Feat: Add notes to order

- src/js/api/order.js
| - | - |
| --- | --- |
| Issue | -- |
> Fix: Remove email param from note creation

- CHANGELOG.md
- src/js/base/api.js
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-vendors-salsa/issues/1 |
Usage:
```javascript
const prices = await this.$ripe.getPricesP({
brand: "cariuma",
model: "oca_low",
configs: [
{
parts: {
base: {
material: "canvas",
color: "all_black"
}
}
}
]
});
```
> feat: getPrices

- CHANGELOG.md
- src/js/visual/configurator-prc.js
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-sdk/issues/307 |
> fix: useMasks calculation

- CHANGELOG.md
- src/js/api/order.js
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-pulse/issues/260|
| Dependencies | https://github.com/ripe-tech/ripe-core/pull/4633 |
| Decisions | Add `refreshShippingOrder` and `refreshShippingOrderP` |
> #260 Refresh shipping methods

- src/js/api/config.js
- src/js/api/size.js
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-sdk/pull/331#discussion_r753332605 |
| Decisions | Fix documentation |
> Fix documentation

- src/python/ripe_demo/static/js/main.js
- test/js/api/attachment.js
- test/js/api/brand.js
- test/js/api/config.js
- test/js/api/mock.js
- test/js/api/notify-info.js
- test/js/api/order.js
- test/js/api/profile.js
- test/js/api/size.js
- test/js/api/sku.js
- test/js/base/api.js
- test/js/base/auth.js
- test/js/config.js
- test/js/locales/base.js
- test/js/visual.js
| - | - |
| --- | --- |
| Issue | Originated via https://github.com/ripe-tech/ripe-pulse/issues/276 |
| Decisions | To run ripe-sdk tests locally, it is useful to change the core instance used. I kept the same default (SBX). |
> test: allow config core instance

- CHANGELOG.md
- package.json
- src/js/base/ripe.js
| - | - |
| --- | --- |
| Decisions | - Release new version to access new sdk methods |
> version: 2.12.0

- CHANGELOG.md
- src/js/base/api.js
| - | - |
| --- | --- |
| Issue | -- |
| Decisions | Added missing compose params to `_getImageOptions`. |
> feat: added missing params to _getImageOptions

- CHANGELOG.md
- src/js/visual/image.js
| - | - |
| --- | --- |
| Issue | -- |
> feat: support width and height in image resize

- CHANGELOG.md
- package.json
- src/js/base/ripe.js
| - | - |
| --- | --- |
| Decisions | - Release new version with newest fixes. |
> version: 2.17.0

- CHANGELOG.md
- src/js/visual/image.js
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/builds-static/pull/2039#discussion_r796827127 |
| Decisions | - Add initials builder `ctx.messages` dispatcher handler for build's js logic  |
> Initials builder ctx message dispatcher

- CHANGELOG.md
- src/js/api/bulk-order.js
- test/js/base/ripe.js
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-pulse/issues/281|
| Decisions | Add missing methods to create a bulk order.|
> #281 Bulking support

- CHANGELOG.md
- src/js/api/bulk-order.js
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-pulse/issues/281 |
| Decisions | Brand is not mandatory, it is computed from the orders. |
> #281: fix import bulk method

- CHANGELOG.md
- package.json
- src/js/base/ripe.js
Required by https://github.com/ripe-tech/ripe-pulse/issues/281
> version: 2.21.0

- CHANGELOG.md
- src/js/api/order.js
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-pulse/issues/301 |
| Dependencies | https://github.com/ripe-tech/ripe-core/pull/4693 |
| Decisions | Add void waybill methods (for both regular and return waybills). |
> feat: void waybills

- CHANGELOG.md
- package.json
- src/js/base/ripe.js
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-pulse/issues/301 |
| Decisions | Release version 2.23.0 |
> version: 2.23.0

- CHANGELOG.md
- package.json
- src/js/base/ripe.js
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-white/issues/993 |
| Decisions | Release version 2.24.0 |
> version: 2.24.0

- CHANGELOG.md
- src/js/api/order.js
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-core/issues/4702 |
| Dependencies | https://github.com/ripe-tech/ripe-core/pull/4706 |
| Decisions | Implement methods to interact with an order's general chat. |
> #4702: General order chat methods

- CHANGELOG.md
- src/js/api/justification.js
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-pulse/issues/317 |
| Dependencies | https://github.com/ripe-tech/ripe-core/pull/4721 |
> feat: resolveJustification method

- CHANGELOG.md
- package.json
- src/js/base/ripe.js
> version: 0.26.0

- CHANGELOG.md
- package.json
- src/js/base/ripe.js
* Added new compose `composeOptions` to allow passing composition options such as dpi and quality.
> version: 2.27.0

- CHANGELOG.md
- src/js/api/order.js
| - | - |
| --- | --- |
| Issue | -- |
| Dependencies | https://github.com/ripe-tech/ripe-core/pull/4726 |
> feat: set order tag and tag activation methods

- CHANGELOG.md
- package.json
- src/js/base/ripe.js
* Added `activateTagOrderP` and `updateTagOrderP` methods to set the tag of an order and activate it
> version: 2.29.0

- CHANGELOG.md
- src/js/api/order.js
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-robin-revamp/issues/363 |
> feat: delete and deactivate order tags

- CHANGELOG.md
- src/js/visual/image.js
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-white/issues/1014#issuecomment-1147233417<br><img width="680" alt="image" src="https://user-images.githubusercontent.com/25725586/172133146-d20e0c84-b795-408b-b15c-8aa2fdc81cb6.png"> |
| Decisions | - Fix initialsSpec profile spread fallback value in image|
> fix: initialsSpec profile spread fallback value in image

- CHANGELOG.md
- package.json
- src/js/base/ripe.js
* Fix initialsSpec profile spread fallback value in image
> version: 2.31.1

- CHANGELOG.md
- README.md
| - | - |
| --- | --- |
| Issue | -- |
| Decisions | How to include our script was asked thrice by external consultors. This information should be enough. |
> docs: update docs with installation steps

- CHANGELOG.md
- src/js/api/brand.js
- src/js/base/api.js
- test/js/api/brand.js
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/project/issues/87 |
|Decisions|Add variant to be passed through `onConfig` and  `onPart`|
> #87 Pass variant through logic methods

- CHANGELOG.md
- gulpfile.js
- src/js/visual/configurator-csr.js
| - | - |
| --- | --- |
| Issue | Need debug tools to analyze the CSR scene |
| Decisions | - Allow the activation of `debug` mode<br>- Allow the activation of framerate, world axis and model group axis debug tools |
https://user-images.githubusercontent.com/22588915/189140456-c8772cf8-3be6-410e-8afd-99f8aa3b5a90.mp4
> CSR debug tools

- CHANGELOG.md
- src/js/visual/configurator-csr.js
| - | - |
| --- | --- |
| Issue | There isn't any zoom feature |
| Decisions |  Add zoom support |
https://user-images.githubusercontent.com/22588915/189408344-794ba60b-e51c-472e-a4fe-fb99fb783d90.mp4
> Add CSR zoom support

- gulpfile.js
- src/js/visual/configurator-csr.js
| - | - |
| --- | --- |
| Issue | Needs proper sync between CSR scene and 3D team Maya scene |
| Decisions | - Sets the default camera settings standard. The values match the values in the Maya scene used by the 3D team.<br>- Allow override of the camera settings via the options and via the loading of a Maya scene<br>- Improve how CSR is initialized |
> Set CSR camera defaults

- CHANGELOG.md
- src/js/visual/configurator-csr.js
- src/js/visual/csr/rendered-initials.js
- src/js/visual/csr/utils.js
| - | - |
| --- | --- |
| Issue | Need to setup CSR initials to be usable by the CSR configurator |
| Dependencies | <del>https://github.com/ripe-tech/ripe-sdk/pull/423</del> |
| Decisions | - Setup CSR initials<br>- Improve debug mode by adding debug tools for the CSR initials<br>- Improve how CSR initials textures resources are handled<br>- Better CSR Initials default values |
https://user-images.githubusercontent.com/22588915/192577319-91960c84-29df-40e4-815c-e9f1474a1e78.mp4
https://user-images.githubusercontent.com/22588915/192577328-8e6e5a72-5aff-4b64-90e6-d8c3752939d1.mp4
> CSR initials setup

- CHANGELOG.md
- src/js/api/order.js
| - | - |
| --- | --- |
| Issue | -- |
| Decisions | Add import order simple methods |
> feat: import order simple methods

- CHANGELOG.md
- src/js/base/api.js
- test/js/base/api.js
| - | - |
| --- | --- |
| Issue | -- |
| Decisions | Add methods for the `GET /api/info` endpoint |
> feat: info method endpoint

- CHANGELOG.md
- package.json
- src/js/base/ripe.js
* Add `quantity` param to `_importOrder` method - [ripe-pulse/#271](https://github.com/ripe-tech/ripe-pulse/issues/271)
> version 2.33.0 :rainbow: 

- CHANGELOG.md
- test/js/config.js
| - | - |
| --- | --- |
| Decisions |- Increase default test timeout given the average SANDBOX test response |
> Increase default test timeout

- CHANGELOG.md
- package.json
- src/js/api/brand.js
- src/js/base/ripe.js
- src/js/visual/configurator-csr.js
| - | - |
| --- | --- |
| Decisions | - Add `get3dSceneEnvironmentUrl`, `getInitials3dBaseTextureUrl` and `getInitials3dDisplacementTextureUrl` |
> #429 Add get URL methods

- CHANGELOG.md
- src/js/api/order.js
| - | - |
| --- | --- |
| Issue | -- |
| Decisions | Optional parameters such as strict and transitions need to be passed. |
> fix: change order status options

- CHANGELOG.md
- src/js/api/order.js
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-core/issues/4700 |
| Dependencies | https://github.com/ripe-tech/ripe-core/pull/4774 |
| Decisions |--|
| Animated GIF |--|
> feat: endpoints to create order issues

- CHANGELOG.md
- package.json
- src/js/base/ripe.js
- src/js/visual/csr/utils.js
* Added SDK methods for orders' issue API endpoints - [ripe-core/#4700](https://github.com/ripe-tech/ripe-core/issues/4700)
> version: 2.35.0

- CHANGELOG.md
- src/js/api/order.js
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-robin-revamp/issues/340 |
| Decisions | - Fix `stateChatLinesOrderP` reference method  |
> #340 Chat Lines: small fix reference method

- test/js/api/config.js
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-sdk/issues/466 |
| Decisions | - Using the newest method `deleteSkuP` to delete skus as already done [here](https://github.com/ripe-tech/ripe-sdk/blob/master/test/js/api/sku.js#L126) |
> #466 Fix test race condition

- CHANGELOG.md
- src/js/api/order.js
- test/js/api/order.js
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-core/issues/4778 |
| Decisions | - Fix failing tests by using `imagesDefault` set to false <br> - Add support for param `imagesDefault` (RIPE Core `images_default`)|
> #4778 Fix tests

- src/js/api/order.js
Ran pretty to fix code style inconsistencies
> style: pretty

- CHANGELOG.md
- src/js/api/brand.js
- src/js/visual/configurator-csr.js
| - | - |
| --- | --- |
| Dependencies | - <del>https://github.com/ripe-tech/ripe-sdk/pull/454</del> <br>- <del>https://github.com/ripe-tech/ripe-core/pull/4770</del><br>- <del>https://github.com/ripe-tech/ripe-sdk/pull/473</del> |
| Decisions | Use texture_map endpoint |
> #429 Use texture_maps endpoint

- CHANGELOG.md
- package.json
- src/js/base/ripe.js
* Add support for post render callback - [#429](https://github.com/ripe-tech/ripe-sdk/issues/429)
* Add support for param `imagesDefault` - [ripe-core/#4778](https://github.com/ripe-tech/ripe-core/issues/4778)
* Add support for global option `authCallback` and improve overall behavior, allowing one request authentication - [ripe-robin-revamp/#416](https://github.com/ripe-tech/ripe-robin-revamp/issues/416)
* Add `getInitialsConfig` , `getInitialsConfigP` and `_getInitialsConfigOptions` methods - [#429](https://github.com/ripe-tech/ripe-sdk/issues/429)
* Load enriched initials config in CSR - [#429](https://github.com/ripe-tech/ripe-sdk/issues/429)
* Support loading of external fonts - [#429](https://github.com/ripe-tech/ripe-sdk/issues/429)
* Returning `authCallback` when requests fails …
> version 2.36.0 :rainbow: 

- CHANGELOG.md
- package.json
- src/js/base/ripe.js
* Support font format in CSR strategy - [#429](https://github.com/ripe-tech/ripe-sdk/issues/429)
* Updated CSR strategy to follow the changes of the updated config - [#429](https://github.com/ripe-tech/ripe-sdk/issues/429)
* Improve CSR loading methodology - [#429](https://github.com/ripe-tech/ripe-sdk/issues/429)
> Version: `2.37.0`

- CHANGELOG.md
- src/js/visual/configurator-csr.js
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-white/issues/1098 |
| Decisions | - Allowing set initials extra of empty or single group initials |
> #1098 Allow basic set initials extra

- CHANGELOG.md
- src/js/base/config.js
- test/js/base/config.js
| - | - |
| --- | --- |
| Dependencies | <del>https://github.com/ripe-tech/ripe-compose/pull/243</del> |
| Decisions | Update `_initialsMerge` to match remote logic |
| Screenshot | ![image](https://user-images.githubusercontent.com/22588915/221546466-88cfa70a-e566-4ff9-88dd-e9c7d8bbe620.png) |
> #429 Update `_initialsMerge` to match remote logic

- CHANGELOG.md
- package.json
- src/js/base/ripe.js
* Add CSR base documentation - [#478](https://github.com/ripe-tech/ripe-sdk/issues/478)
* Add CSR documentation `Dockerfile` - [#478](https://github.com/ripe-tech/ripe-sdk/issues/478)
* Update `initialsConfig()` to match remote logic - [#429](https://github.com/ripe-tech/ripe-sdk/issues/429)
* Update `.gitignore` to ignore CSR documentation compilation files - [#478](https://github.com/ripe-tech/ripe-sdk/issues/478)
* Update CSR documentation with proper configuration with title and logo - [#478](https://github.com/ripe-tech/ripe-sdk/issues/478)
* Improve CSR deinitialization logic - [#493](https://github.com/ripe-tech/ripe-sdk/issues/493)
* Fix div tag outside code block in CSR documentation - [#478](https://github.com/ripe-tech/ripe-sdk/issues/478)
> version 2.40.0 :rainbow: 

- CHANGELOG.md
- src/js/api/order.js
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-core/issues/4798 |
> feat: sku and domain in import order

- .github/workflows/deploy.yml
- .github/workflows/main.yml
- https://github.com/ripe-tech/ripe-bridge/pull/358#discussion_r1234879515
- None
- As of 2023-04-30 Node 14 reached EOL 
- None
> feat: review node versions

- CHANGELOG.md
- src/js/base/api.js
- src/js/base/ripe.js
- test/js/base/api.js
- test/js/config.js
- https://github.com/ripe-tech/products/issues/132
- None
- Added `composeUrl` option to allow custom for composition endpoints
- None
> #132 Custom compose url

- CHANGELOG.md
- package.json
- src/js/base/ripe.js
* Added `composeUrl` option to allow custom for composition endpoints - [products/#132](https://github.com/ripe-tech/products/issues/132)
* Change API testing provider from `httpbin` to `postman-echo`
> version 3.1.0 :rainbow: 

- CHANGELOG.md
- src/js/api/admin/event.js
- src/js/api/admin/index.js
- src/js/api/index.js
- src/js/visual/configurator-prc.js
- https://github.com/ripe-tech/ripe-core/issues/4828
- https://github.com/ripe-tech/ripe-core/pull/4842
- Add the LCRUD endpoints for the event API
- None
> feat: event API

- CHANGELOG.md
- src/js/api/shipment.js
- https://github.com/ripe-tech/ripe-core/issues/4853
> feat: create waybill and invoice for shipments

- CHANGELOG.md
- src/js/api/shipment.js
- https://github.com/ripe-tech/ripe-core/issues/4853
> feat: shipment status update methods

- CHANGELOG.md
- src/js/api/shipment.js
- https://github.com/ripe-tech/ripe-pulse/issues/396
> feat: add shipment notes & issues

- CHANGELOG.md
- package.json
- src/js/base/ripe.js
* Added waybill and invoice creation methods to the `ShipmentAPI` - [#4853](https://github.com/ripe-tech/ripe-core/issues/4853)
* Added shipment attachment methods to the `ShipmentAPI` - [#4853](https://github.com/ripe-tech/ripe-core/issues/4853)
* Added shipment status change methods to the `ShipmentAPI` - [#4853](https://github.com/ripe-tech/ripe-core/issues/4853)
* Added shipment notes and issues methods - [ripe-pulse/#396](https://github.com/ripe-tech/ripe-pulse/issues/396)
> version: 3.3.0

- CHANGELOG.md
- src/js/api/shipment.js
- https://github.com/ripe-tech/ripe-pulse/issues/396
> feat: add create document RIPE SDK

- CHANGELOG.md
- package.json
- src/js/base/ripe.js
* Added create documents for shipping API - [ripe-pulse/#396](https://github.com/ripe-tech/ripe-pulse/issues/396)
> version: 3.3.1
